/*
 * SimpleGLJPanel.java
 *
 * Created on 30. Juli 2008, 16:18
 */
package org.yourorghere;

import com.sun.opengl.util.Animator;
import java.awt.EventQueue;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.media.opengl.GLCapabilities;
import javax.media.opengl.GLJPanel;
import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.WindowConstants;
import java.awt.Button;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import javax.swing.BorderFactory;

/**
 *
 * @author cylab
 * @author mbien
 */
public class Main extends JFrame
{
    
    private Animator animator;
    SelecNivel levels = new SelecNivel();
    Creditos2 cr = new Creditos2();
    GLRenderMain rend;
    Instrucciones ins = new Instrucciones();

    /**
     * Creates new form MainFrame
     */
    public Main()
    {
        initComponents();
        setTitle("Aprende a Programar");
        
        rend = new GLRenderMain();
        panel.addGLEventListener(rend);
        animator = new Animator(panel);
        
        this.addWindowListener(new WindowAdapter()
        {
            @Override
            public void windowClosing(WindowEvent e)
            {
                // Run this on another thread than the AWT event queue to
                // make sure the call to Animator.stop() completes before
                // exiting
                new Thread(new Runnable()
                {
                    public void run()
                    {
                        animator.stop();
                        System.exit(0);
                    }
                }).start();
            }
        });
    }
    
    @Override
    public void setVisible(boolean show)
    {
        if (!show)
        {
            animator.stop();
        }
        super.setVisible(show);
        if (!show)
        {
            animator.start();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        button1 = new Button();
        panel = new GLJPanel(createGLCapabilites());
        jButtonCreditos = new JButton();
        jButtonInstrucciones = new JButton();
        jButtonJugar = new JButton();

        button1.setLabel("button1");

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("TAG");
        setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        setForeground(Color.gray);

        jButtonCreditos.setText("Créditos");
        jButtonCreditos.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        jButtonCreditos.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                jButtonCreditosActionPerformed(evt);
            }
        });

        jButtonInstrucciones.setText("Instrucciones");
        jButtonInstrucciones.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        jButtonInstrucciones.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                jButtonInstruccionesActionPerformed(evt);
            }
        });

        jButtonJugar.setText("Jugar");
        jButtonJugar.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        jButtonJugar.addActionListener(new ActionListener()
        {
            public void actionPerformed(ActionEvent evt)
            {
                jButtonJugarActionPerformed(evt);
            }
        });

        GroupLayout panelLayout = new GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(panelLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(228, Short.MAX_VALUE)
                .addComponent(jButtonJugar, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonInstrucciones, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCreditos, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        panelLayout.setVerticalGroup(panelLayout.createParallelGroup(Alignment.LEADING)
            .addGroup(Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(470, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(Alignment.TRAILING, false)
                    .addComponent(jButtonCreditos, GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jButtonJugar, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(jButtonInstrucciones, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(Alignment.LEADING)
            .addComponent(panel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
            .addComponent(panel, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonJugarActionPerformed(ActionEvent evt)//GEN-FIRST:event_jButtonJugarActionPerformed
    {//GEN-HEADEREND:event_jButtonJugarActionPerformed
        
        levels.setVisible(true);
    }//GEN-LAST:event_jButtonJugarActionPerformed

    private void jButtonCreditosActionPerformed(ActionEvent evt)//GEN-FIRST:event_jButtonCreditosActionPerformed
    {//GEN-HEADEREND:event_jButtonCreditosActionPerformed
        cr.setVisible(true);
    }//GEN-LAST:event_jButtonCreditosActionPerformed

    private void jButtonInstruccionesActionPerformed(ActionEvent evt)//GEN-FIRST:event_jButtonInstruccionesActionPerformed
    {//GEN-HEADEREND:event_jButtonInstruccionesActionPerformed
        ins.setVisible(true);
    }//GEN-LAST:event_jButtonInstruccionesActionPerformed

    /**
     * Called from within initComponents(). hint: to customize the generated
     * code choose 'Customize Code' in the contextmenu of the selected UI
     * Component you wish to cutomize in design mode.
     *
     * @return Returns customized GLCapabilities.
     */
    private GLCapabilities createGLCapabilites()
    {
        
        GLCapabilities capabilities = new GLCapabilities();
        capabilities.setHardwareAccelerated(true);

        // try to enable 2x anti aliasing - should be supported on most hardware
        capabilities.setNumSamples(2);
        capabilities.setSampleBuffers(true);
        
        return capabilities;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        // Run this in the AWT event thread to prevent deadlocks and race conditions
        EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {

                // switch to system l&f for native font rendering etc.
                try
                {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (Exception ex)
                {
                    Logger.getLogger(getClass().getName()).log(Level.INFO, "can not enable system look and feel", ex);
                }
                
                Main frame = new Main();
                frame.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Button button1;
    private JButton jButtonCreditos;
    private JButton jButtonInstrucciones;
    private JButton jButtonJugar;
    private GLJPanel panel;
    // End of variables declaration//GEN-END:variables
}
